# Generated by Django 3.1.6 on 2021-02-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_selling_price',
            field=models.FloatField(default=None),
        ),
    ]
